emotion_subject_dict = {'bored': ['suburban_life','fiction'],
                        'loving':['young women','fiction']
                        'intimte':[ 'young women','fiction']
                        'disllusioned':['depression','fiction']
                        'adventerous':['travel','Survival after airplane accidents, shipwrecks']
                        'aviodance':['fiction','guilt']
                        'guilty':['fiction','guilt']
                        'abandoned':['fiction','orphans']
                        'despair':['fiction','empty']
                        'depressed':['fiction','mentally_ill']
                        'lonely':['fiction','orphans']
                        'bored':['fiction','suburbn_life']
                        'optimistic':['fiction','self-realization_in_women','self-reliazation']
                        'peaceful':['fiction','spirituality']
                        'powerful':['fiction','human-animal_relationship']
                        'accepted':['fiction','compassion']
                        'proud':['fiction','pride']
                        'inquisitive':['fiction','american_science_fiction']
                        'joyful':['fiction','comedy']
                        'excited':['fiction','hard']
                        'amazed':['fiction','hard']
                        'confused':['fiction','runaway']
                        'scared':['fiction','sucide_victims']
                        'anxious':['fiction','thriller']
                        'rejected':['fiction','illegitimacy']
                        'hurt':['fiction','married women','adultery','historical fiction']
                        'threatened':['fiction','jealousy']
                        'mad':['fiction','revenge','psychopaths']
                        'hateful':['fiction','revenge','psychopaths']
                        'aggressive':['fiction','war']
                        'distant':['fiction','interpersonal_relations']
                        'critical':['fiction','history_and_criticism']
                        'repressed':['fiction','puritan']
                        'heroic':['fiction','individualism']
                        }
                        
                        
                        
