emotion_subject_dict = {
                        'bored': ['suburban_life','fiction'],
                        'loving':['young women','fiction'],
                        'intimate':[ 'young women','fiction'],
                        'disillusioned':['depression','fiction'],
                        'adventurous':['travel','Survival_after_airplane_accidents, shipwrecks'],
                        'avoidance':['fiction','guilt'],
                        'guilty':['fiction','guilt'],
                        'abandoned':['fiction','orphans'],
                        'despair':['empty'],
                        'depressed':['fiction','mentally_ill'],
                        'lonely':['fiction','orphans'],
                        'optimistic':['self-realization'],
                        'peaceful':['fiction','spirituality'],
                        'powerful':['fiction','human-animal_relationship'],
                        'accepted':['compassion'],
                        'proud':['fiction','pride'],
                        'inquisitive':['fiction','american_science_fiction'],
                        'joyful':['fiction','comedy'],
                        'excited':['fiction','hard'],
                        'amazed':['fiction','hard'],
                        'confused':['fiction','runaway'],
                        'scared':['fiction','suicide_victims'],
                        'anxious':['fiction','thriller'],
                        'rejected':['illegitimacy'],
                        'hurt':['fiction', 'historical_fiction'],
                        'threatened':['fiction','jealousy'],
                        'mad':['fiction','murderers'],
                        'hate':['fiction','revenge'],
                        'aggressive':['fiction','war'],
                        'distant':['fiction','interpersonal_relations'],
                        'critical':['fiction','history_and_criticism'],
                        'repressed':['fiction','puritan'],
                        'heroic':['fiction','individualism'],
                        }
                        
                        
                        
